apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs 
spec:
  capacity:
    storage: 2Gi 
  storageClassName: manual
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /nfs-test 
    server:  
  persistentVolumeReclaimPolicy: Recycle 
